/*
 *  TMC0490_Mask_Shift.h
 *  Author: LK
 *  Generated by MaskShiftConverter (unchecked)
 */

#ifndef TMC0490_MASK_SHIFT_H
#define TMC0490_MASK_SHIFT_H

	#define TMC0490_SI_TYPE_MASK                      0xFFFFFFFF // CHIPINFO_DATA //
	#define TMC0490_SI_TYPE_SHIFT                     0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_SI_VERSION_MASK                   0xFFFFFFFF // CHIPINFO_DATA //
	#define TMC0490_SI_VERSION_SHIFT                  0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_SI_DATE_MASK                      0xFFFFFFFF // CHIPINFO_DATA //
	#define TMC0490_SI_DATE_SHIFT                     0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_SI_TIME_MASK                      0xFFFFFFFF // CHIPINFO_DATA //
	#define TMC0490_SI_TIME_SHIFT                     0 // min.: 0, max.: 16777215, default: 0
	#define TMC0490_CHIP_INFO_ADDRESS_MASK            0xFF // CHIPINFO_ADDR //
	#define TMC0490_CHIP_INFO_ADDRESS_SHIFT           0 // min.: 0, max.: 3, default: 0
	#define TMC0490_STATUS_WORD_MASK                  0xFFFF // STATUS_WORD // description of STATUS_WORD
	#define TMC0490_STATUS_WORD_SHIFT                 0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_COMMAND_WORD_MASK                 0xFFFFFFFF // COMMAND_WORD // description of COMMAND_WORD
	#define TMC0490_COMMAND_WORD_SHIFT                0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_P_FAK_BUCK_MASK                   0xFFFF // P_FAK_BUCK // description of P_FAK_BUCK
	#define TMC0490_P_FAK_BUCK_SHIFT                  0 // min.: 0, max.: 32767, default: 0
	#define TMC0490_I_FAK_BUCK_MASK                   0xFFFF // I_FAK_BUCK // description of I_FAK_BUCK
	#define TMC0490_I_FAK_BUCK_SHIFT                  0 // min.: 0, max.: 32767, default: 0
	#define TMC0490_P_FAK_BOOST_MASK                  0xFFFF // P_FAK_BOOST // description of P_FAK_BOOST
	#define TMC0490_P_FAK_BOOST_SHIFT                 0 // min.: 0, max.: 32767, default: 0
	#define TMC0490_I_FAK_BOOST_MASK                  0xFFFF // I_FAK_BOOST // description of I_FAK_BOOST
	#define TMC0490_I_FAK_BOOST_SHIFT                 0 // min.: 0, max.: 32767, default: 0
	#define TMC0490_U_MAX_RAIL_MASK                   0xFFFF // U_MAX_RAIL // description of U_MAX_RAIL
	#define TMC0490_U_MAX_RAIL_SHIFT                  0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_U_MIN_RAIL_MASK                   0xFFFF // U_MIN_RAIL // description of U_MIN_RAIL
	#define TMC0490_U_MIN_RAIL_SHIFT                  0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_U_MAX_SCAP_MASK                   0xFFFF // U_MAX_SCAP // description of U_MAX_SCAP
	#define TMC0490_U_MAX_SCAP_SHIFT                  0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_U_MIN_SCAP_MASK                   0xFFFF // U_MIN_SCAP // description of U_MIN_SCAP
	#define TMC0490_U_MIN_SCAP_SHIFT                  0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_U_NOM_RAIL_MASK                   0xFFFF // U_NOM_RAIL // description of U_NOM_RAIL
	#define TMC0490_U_NOM_RAIL_SHIFT                  0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_DELTA_VOLT_MASK                   0xFFFF // DELTA_VOLT // description of DELTA_VOLT
	#define TMC0490_DELTA_VOLT_SHIFT                  0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_U_TARGET_RAIL_MASK                0xFFFF // U_TARGET_RAIL // description of U_TARGET_RAIL
	#define TMC0490_U_TARGET_RAIL_SHIFT               0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_I_MAX_SW_MASK                     0xFFFF // I_MAX_SW // description of I_MAX_SW
	#define TMC0490_I_MAX_SW_SHIFT                    0 // min.: 0, max.: 32767, default: 0
	#define TMC0490_I_MAX_RAIL_MASK                   0xFFFF // I_MAX_RAIL // description of I_MAX_RAIL
	#define TMC0490_I_MAX_RAIL_SHIFT                  0 // min.: 0, max.: 32767, default: 0
	#define TMC0490_OSCI_MAIN_CONFIG_REG_MASK         0xFFFFFFFF // OSCI_MAIN_CONFIG_REG // description of OSCI_MAIN_CONFIG_REG
	#define TMC0490_OSCI_MAIN_CONFIG_REG_SHIFT        0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_OSCI_PRETRIGGER_CONFIG_REG_MASK   0xFFFF // OSCI_PRETRIGGER_CONFIG_REG // description of OSCI_PRETRIGGER_CONFIG_REG
	#define TMC0490_OSCI_PRETRIGGER_CONFIG_REG_SHIFT  0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_OSCI_DATA_ADDRESS_MASK            0xFFFF // OSCI_DATA_ADDRESS // description of OSCI_DATA_ADDRESS
	#define TMC0490_OSCI_DATA_ADDRESS_SHIFT           0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_OSCI_STATUS_MASK                  0xFFFF // OSCI_STATUS // description of OSCI_STATUS
	#define TMC0490_OSCI_STATUS_SHIFT                 0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_OSCI_OUTPUT_DATA_MASK             0xFFFFFFFF // OSCI_OUTPUT_DATA // description of OSCI_OUTPUT_DATA
	#define TMC0490_OSCI_OUTPUT_DATA_SHIFT            0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_ADC_I_RAIL_RAW_MASK               0xFFFF // ADC_I_RAIL_RAW // description of ADC_I_RAIL_RAW
	#define TMC0490_ADC_I_RAIL_RAW_SHIFT              0 // min.: 0, max.: 32767, default: 0
	#define TMC0490_ADC_I_SW_RAW_MASK                 0xFFFF // ADC_I_SW_RAW // description of ADC_I_SW_RAW
	#define TMC0490_ADC_I_SW_RAW_SHIFT                0 // min.: 0, max.: 32767, default: 0
	#define TMC0490_ADC_U_RAIL_RAW_MASK               0xFFFF // ADC_U_RAIL_RAW // description of ADC_U_RAIL_RAW
	#define TMC0490_ADC_U_RAIL_RAW_SHIFT              0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_ADC_U_CAP_RAW_MASK                0xFFFF // ADC_U_CAP_RAW // description of ADC_U_CAP_RAW
	#define TMC0490_ADC_U_CAP_RAW_SHIFT               0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_PWM_VALUE_HS_MASK                 0xFFFF // PWM_VALUE_HS // description of PWM_VALUE_HS
	#define TMC0490_PWM_VALUE_HS_SHIFT                0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_PWM_VALUE_LS_MASK                 0xFFFF // PWM_VALUE_LS // description of PWM_VALUE_LS
	#define TMC0490_PWM_VALUE_LS_SHIFT                0 // min.: 0, max.: 65535, default: 0
	#define TMC0490_I_STATE_BUCK_MASK                 0xFFFFFFFF // I_STATE_BUCK // description of I_STATE_BUCK
	#define TMC0490_I_STATE_BUCK_SHIFT                0 // min.: 0, max.: 2147483647, default: 0
	#define TMC0490_I_STATE_BOOST_MASK                0xFFFFFFFF // I_STATE_BOOST // description of I_STATE_BOOST
	#define TMC0490_I_STATE_BOOST_SHIFT               0 // min.: 0, max.: 2147483647, default: 0
	#define TMC0490_DEBUG_AXIS_PARAM_0_MASK           0xFFFFFFFF // DEBUG_AXIS_PARAM_0 // description of DEBUG_AXIS_PARAM_0
	#define TMC0490_DEBUG_AXIS_PARAM_0_SHIFT          0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_DEBUG_AXIS_PARAM_1_MASK           0xFFFFFFFF // DEBUG_AXIS_PARAM_1 // description of DEBUG_AXIS_PARAM_1
	#define TMC0490_DEBUG_AXIS_PARAM_1_SHIFT          0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_DEBUG_AXIS_PARAM_2_MASK           0xFFFFFFFF // DEBUG_AXIS_PARAM_2 // description of DEBUG_AXIS_PARAM_2
	#define TMC0490_DEBUG_AXIS_PARAM_2_SHIFT          0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_DEBUG_AXIS_PARAM_3_MASK           0xFFFFFFFF // DEBUG_AXIS_PARAM_3 // description of DEBUG_AXIS_PARAM_3
	#define TMC0490_DEBUG_AXIS_PARAM_3_SHIFT          0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_DEBUG_AXIS_PARAM_4_MASK           0xFFFFFFFF // DEBUG_AXIS_PARAM_4 // description of DEBUG_AXIS_PARAM_4
	#define TMC0490_DEBUG_AXIS_PARAM_4_SHIFT          0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_DEBUG_AXIS_PARAM_5_MASK           0xFFFFFFFF // DEBUG_AXIS_PARAM_5 // description of DEBUG_AXIS_PARAM_5
	#define TMC0490_DEBUG_AXIS_PARAM_5_SHIFT          0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_DEBUG_AXIS_PARAM_6_MASK           0xFFFFFFFF // DEBUG_AXIS_PARAM_6 // description of DEBUG_AXIS_PARAM_6
	#define TMC0490_DEBUG_AXIS_PARAM_6_SHIFT          0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_DEBUG_AXIS_PARAM_7_MASK           0xFFFFFFFF // DEBUG_AXIS_PARAM_7 // description of DEBUG_AXIS_PARAM_7
	#define TMC0490_DEBUG_AXIS_PARAM_7_SHIFT          0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_STATE_VAR_PARAM_0_MASK            0xFFFFFFFF // STATE_VAR_PARAM_0 // description of STATE_VAR_PARAM_0
	#define TMC0490_STATE_VAR_PARAM_0_SHIFT           0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_STATE_VAR_PARAM_1_MASK            0xFFFFFFFF // STATE_VAR_PARAM_1 // description of STATE_VAR_PARAM_1
	#define TMC0490_STATE_VAR_PARAM_1_SHIFT           0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_STATE_VAR_PARAM_2_MASK            0xFFFFFFFF // STATE_VAR_PARAM_2 // description of STATE_VAR_PARAM_2
	#define TMC0490_STATE_VAR_PARAM_2_SHIFT           0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_STATE_VAR_PARAM_3_MASK            0xFFFFFFFF // STATE_VAR_PARAM_3 // description of STATE_VAR_PARAM_3
	#define TMC0490_STATE_VAR_PARAM_3_SHIFT           0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_STATE_VAR_PARAM_4_MASK            0xFFFFFFFF // STATE_VAR_PARAM_4 // description of STATE_VAR_PARAM_4
	#define TMC0490_STATE_VAR_PARAM_4_SHIFT           0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_STATE_VAR_PARAM_5_MASK            0xFFFFFFFF // STATE_VAR_PARAM_5 // description of STATE_VAR_PARAM_5
	#define TMC0490_STATE_VAR_PARAM_5_SHIFT           0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_STATE_VAR_PARAM_6_MASK            0xFFFFFFFF // STATE_VAR_PARAM_6 // description of STATE_VAR_PARAM_6
	#define TMC0490_STATE_VAR_PARAM_6_SHIFT           0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_STATE_VAR_PARAM_7_MASK            0xFFFFFFFF // STATE_VAR_PARAM_7 // description of STATE_VAR_PARAM_7
	#define TMC0490_STATE_VAR_PARAM_7_SHIFT           0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_SCU_INPUTS_RAW_MASK               0xFFFFFFFF // SCU_INPUTS_RAW // description of SCU_INPUTS_RAW
	#define TMC0490_SCU_INPUTS_RAW_SHIFT              0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_SCU_OUTPUTS_RAW_MASK              0xFFFFFFFF // SCU_OUTPUTS_RAW // description of SCU_OUTPUTS_RAW
	#define TMC0490_SCU_OUTPUTS_RAW_SHIFT             0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_STATUS_FLAGS_MASK                 0xFFFFFFFF // STATUS_FLAGS // description of STATUS_FLAGS
	#define TMC0490_STATUS_FLAGS_SHIFT                0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_WARNING_MASK_MASK                 0xFFFFFFFF // WARNING_MASK // description of WARNING_MASK
	#define TMC0490_WARNING_MASK_SHIFT                0 // min.: 0, max.: 4294967295, default: 0
	#define TMC0490_ERROR_MASK_MASK                   0xFFFFFFFF // ERROR_MASK // description of ERROR_MASK
	#define TMC0490_ERROR_MASK_SHIFT                  0 // min.: 0, max.: 4294967295, default: 0

	// Trigger channel
	#define TMC0490_TRG_CHN_MASK                      0x070000
	#define TMC0490_TRG_CHN_SHIFT                     16
	// Trigger condition
	#define TMC0490_TRG_CND_MASK                      0xF80000
	#define TMC0490_TRG_CND_SHIFT                     19
	// Trigger value
	#define TMC0490_TRG_VAL_MASK                      0xFFFF
	#define TMC0490_TRG_VAL_SHIFT                     0
	// Oversampling ratio
	#define TMC0490_OSR_MASK                          0x07000000
	#define TMC0490_OSR_SHIFT                         24
	// Data sampling rate
	#define TMC0490_DSR_MASK                          0x38000000
	#define TMC0490_DSR_SHIFT                         27
	// Enable/disable measurement
	#define TMC0490_MEAS_EN_MASK                      0x40000000
	#define TMC0490_MEAS_EN_SHIFT                     30
	// Clear measurement
	#define TMC0490_MEAS_CLR_MASK                     0x80000000
	#define TMC0490_MEAS_CLR_SHIFT                    31

#endif /* TMC0490_MASK_SHIFT_H */
