/*
 *  TMC2130_Mask_Shift.h
 *  Author: LK
 *  Generated by MaskShiftConverter (unchecked)
 */

#ifndef TMC2130_MASK_SHIFT_H
#define TMC2130_MASK_SHIFT_H

	#define TMC2130_I_SCALE_ANALOG_MASK                   0x01 // GCONF //
	#define TMC2130_I_SCALE_ANALOG_SHIFT                  0 // min.: 0, max.: 1, default: 0
	#define TMC2130_INTERNAL_RSENSE_MASK                  0x02 // GCONF //
	#define TMC2130_INTERNAL_RSENSE_SHIFT                 1 // min.: 0, max.: 1, default: 0
	#define TMC2130_EN_PWM_MODE_MASK                      0x04 // GCONF //
	#define TMC2130_EN_PWM_MODE_SHIFT                     2 // min.: 0, max.: 1, default: 0
	#define TMC2130_ENC_COMMUTATION_MASK                  0x08 // GCONF //
	#define TMC2130_ENC_COMMUTATION_SHIFT                 3 // min.: 0, max.: 1, default: 0
	#define TMC2130_SHAFT_MASK                            0x10 // GCONF //
	#define TMC2130_SHAFT_SHIFT                           4 // min.: 0, max.: 1, default: 0
	#define TMC2130_DIAG0_ERROR_ONLY_WITH_SD_MODE1_MASK   0x20 // GCONF //
	#define TMC2130_DIAG0_ERROR_ONLY_WITH_SD_MODE1_SHIFT  5 // min.: 0, max.: 1, default: 0
	#define TMC2130_DIAG0_OTPW_ONLY_WITH_SD_MODE1_MASK    0x40 // GCONF //
	#define TMC2130_DIAG0_OTPW_ONLY_WITH_SD_MODE1_SHIFT   6 // min.: 0, max.: 1, default: 0
	#define TMC2130_DIAG0_STALL_MASK                      0x80 // GCONF //
	#define TMC2130_DIAG0_STALL_SHIFT                     7 // min.: 0, max.: 1, default: 0
	#define TMC2130_DIAG1_STALL_MASK                      0x0100 // GCONF //
	#define TMC2130_DIAG1_STALL_SHIFT                     8 // min.: 0, max.: 1, default: 0
	#define TMC2130_DIAG1_INDEX_MASK                      0x0200 // GCONF //
	#define TMC2130_DIAG1_INDEX_SHIFT                     9 // min.: 0, max.: 1, default: 0
	#define TMC2130_DIAG1_ONSTATE_MASK                    0x0400 // GCONF //
	#define TMC2130_DIAG1_ONSTATE_SHIFT                   10 // min.: 0, max.: 1, default: 0
	#define TMC2130_DIAG1_STEPS_SKIPPED_MASK              0x0800 // GCONF //
	#define TMC2130_DIAG1_STEPS_SKIPPED_SHIFT             11 // min.: 0, max.: 1, default: 0
	#define TMC2130_DIAG0_INT_PUSHPULL_MASK               0x1000 // GCONF //
	#define TMC2130_DIAG0_INT_PUSHPULL_SHIFT              12 // min.: 0, max.: 1, default: 0
	#define TMC2130_DIAG1_POSCOMP_PUSHPULL_MASK           0x2000 // GCONF //
	#define TMC2130_DIAG1_POSCOMP_PUSHPULL_SHIFT          13 // min.: 0, max.: 1, default: 0
	#define TMC2130_SMALL_HYSTERESIS_MASK                 0x4000 // GCONF //
	#define TMC2130_SMALL_HYSTERESIS_SHIFT                14 // min.: 0, max.: 1, default: 0
	#define TMC2130_STOP_ENABLE_MASK                      0x8000 // GCONF //
	#define TMC2130_STOP_ENABLE_SHIFT                     15 // min.: 0, max.: 1, default: 0
	#define TMC2130_DIRECT_MODE_MASK                      0x010000 // GCONF //
	#define TMC2130_DIRECT_MODE_SHIFT                     16 // min.: 0, max.: 1, default: 0
	#define TMC2130_TEST_MODE_MASK                        0x020000 // GCONF //
	#define TMC2130_TEST_MODE_SHIFT                       17 // min.: 0, max.: 1, default: 0
	#define TMC2130_RESET_MASK                            0x01 // GSTAT //
	#define TMC2130_RESET_SHIFT                           0 // min.: 0, max.: 1, default: 0
	#define TMC2130_DRV_ERR_MASK                          0x02 // GSTAT //
	#define TMC2130_DRV_ERR_SHIFT                         1 // min.: 0, max.: 1, default: 0
	#define TMC2130_UV_CP_MASK                            0x04 // GSTAT //
	#define TMC2130_UV_CP_SHIFT                           2 // min.: 0, max.: 1, default: 0
	#define TMC2130_REFL_STEP_MASK                        0x01 // IOIN // REFL_STEP
	#define TMC2130_REFL_STEP_SHIFT                       0 // min.: 0, max.: 1, default: 0
	#define TMC2130_REFR_DIR_MASK                         0x02 // IOIN // REFR_DIR
	#define TMC2130_REFR_DIR_SHIFT                        1 // min.: 0, max.: 1, default: 0
	#define TMC2130_ENCB_DCEN_CFG4_MASK                   0x04 // IOIN // ENCB_DCEN_CFG4
	#define TMC2130_ENCB_DCEN_CFG4_SHIFT                  2 // min.: 0, max.: 1, default: 0
	#define TMC2130_ENCA_DCIN_CFG5_MASK                   0x08 // IOIN // ENCA_DCIN_CFG5
	#define TMC2130_ENCA_DCIN_CFG5_SHIFT                  3 // min.: 0, max.: 1, default: 0
	#define TMC2130_DRV_ENN_CFG6_MASK                     0x10 // IOIN // DRV_ENN_CFG6
	#define TMC2130_DRV_ENN_CFG6_SHIFT                    4 // min.: 0, max.: 1, default: 0
	#define TMC2130_ENC_N_DCO_MASK                        0x20 // IOIN // ENC_N_DCO
	#define TMC2130_ENC_N_DCO_SHIFT                       5 // min.: 0, max.: 1, default: 0
	#define TMC2130_VERSION_MASK                          0xFF000000 // IOIN // VERSION: 0x11=first version of the IC; Identical numbers mean full digital compatibility.
	#define TMC2130_VERSION_SHIFT                         24 // min.: 0, max.: 255, default: 0
	#define TMC2130_IHOLD_MASK                            0x1F // IHOLD_IRUN // Standstill current (0=1/32...31=32/32) In combination with stealthChop mode, setting IHOLD=0 allows to choose freewheeling or coil short circuit (passive braking) for motor stand still.
	#define TMC2130_IHOLD_SHIFT                           0 // min.: 0, max.: 31, default: 0
	#define TMC2130_IRUN_MASK                             0x1F00 // IHOLD_IRUN // Motor run current (0=1/32...31=32/32) Hint: Choose sense resistors in a way, that normal IRUN is 16 to 31 for best microstep performance.
	#define TMC2130_IRUN_SHIFT                            8 // min.: 0, max.: 31, default: 0
	#define TMC2130_IHOLDDELAY_MASK                       0x0F0000 // IHOLD_IRUN // Controls the number of clock cycles for motor power down after standstill is detected (stst=1) and TPOWERDOWN has expired. The smooth transition avoids a motor jerk upon power down. 0:  instant power down 1..15:  Delay per current reduction step in multiple of 2^18 clocks
	#define TMC2130_IHOLDDELAY_SHIFT                      16 // min.: 0, max.: 15, default: 0
	#define TMC2130_TPOWERDOWN_MASK                       0xFF // TPOWERDOWN // (Reset default=20) Sets the delay time from stand still (stst) detection to motor current power down. Time range is about 0 to 5.6 seconds. 0...((2^8)-1) * 2^18 tclk Attention: A minimum setting of 2 is required to allow automatic tuning of stealthChop PWM_OFFS_AUTO.
	#define TMC2130_TPOWERDOWN_SHIFT                      0 // min.: 0, max.: 255, default: 0
	#define TMC2130_TSTEP_MASK                            0x0FFFFF // TSTEP // Actual measured time between two 1/256 microsteps derived from the step input frequency in units of 1/fCLK. Measured value is (2^20)-1 in case of overflow or stand still. The TSTEP related threshold uses a hysteresis of 1/16 of the compare value to compensate for jitter in the clock or the step frequency: (Txxx*15/16)-1 is the lower compare value for each TSTEP based comparison. This means, that the lower switching velocity equals the calculated setting, but the upper switching velocity is higher as defined by the hysteresis setting.
	#define TMC2130_TSTEP_SHIFT                           0 // min.: 0, max.: 1048575, default: 0
	#define TMC2130_TPWMTHRS_MASK                         0x0FFFFF // TPWMTHRS // Sets the upper velocity for stealthChop voltage PWM mode.     For TSTEP = TPWMTHRS, stealthChop PWM mode is enabled, if configured. When the velocity exceeds the limit set by TPWMTHRS, the driver switches to spreadCycle. 0 = Disabled
	#define TMC2130_TPWMTHRS_SHIFT                        0 // min.: 0, max.: 1048575, default: 0
	#define TMC2130_TCOOLTHRS_MASK                        0x0FFFFF // TCOOLTHRS // This is the lower threshold velocity for switching on smart energy coolStep and stallGuard feature. (unsigned) Set this parameter to disable coolStep at low speeds, where it cannot work reliably. The stop on stall function (enable with sg_stop when using internal motion controller) and the stall output signal become enabled when exceeding this velocity. In non-dcStep mode, it becomes disabled again once the velocity falls below this threshold. TCOOLTHRS = TSTEP = THIGH: - coolStep is enabled, if configured - stealthChop voltage PWM mode is disabled TCOOLTHRS = TSTEP - Stop on stall and stall output signal is enabled, if configured
	#define TMC2130_TCOOLTHRS_SHIFT                       0 // min.: 0, max.: 1048575, default: 0
	#define TMC2130_THIGH_MASK                            0x0FFFFF // THIGH // This velocity setting allows velocity dependent switching into a different chopper mode and fullstepping to maximize torque. (unsigned) The stall detection feature becomes switched off for 2-3 electrical periods whenever passing THIGH threshold to compensate for the effect of switching modes. TSTEP = THIGH: - coolStep is disabled (motor runs with normal current scale) - stealthChop voltage PWM mode is disabled - If vhighchm is set, the chopper switches to chm=1 with TFD=0 (constant off time with slow decay, only). - chopSync2 is switched off (SYNC=0) - If vhighfs is set, the motor operates in fullstep mode and the stall detection becomes switched over to dcStep stall detection.
	#define TMC2130_THIGH_SHIFT                           0 // min.: 0, max.: 1048575, default: 0
	//#define TMC2130_DIRECT_MODE_MASK                    0xFFFFFF // XDIRECT // 0: Normal operation; 1: Directly SPI driven motor current; Direct mode operation: XDIRECT specifies Motor coil currents and polarity directly programmed via the serial interface. Use signed, two’s complement numbers. Coil A current (bits 8..0) (signed); Coil B current (bits 24..16) (signed); Range: +-248 for normal operation, up to +-255 with stealthChop; In this mode, the current is scaled by IHOLD setting. Velocity based current regulation of voltage PWM is not available in this mode. The automatic voltage PWM current regulation will work only for low stepper motor velocities. dcStep is not available in this mode. coolStep and stallGuard only can be used, when additionally supplying a STEP signal. This will also enable automatic current scaling.
	//#define TMC2130_DIRECT_MODE_SHIFT                   0 // min.: -255, max.: 255, default: 0
	#define TMC2130_VDCMIN_MASK                           0x07FFFFFF // VDCMIN // Automatic commutation dcStep becomes enabled above velocity VDCMIN (unsigned) (only when using internal ramp generator, not for STEP/DIR interface – in STEP/DIR mode, dcStep becomes enabled by the external signal DCEN) In this mode, the actual position is determined by the sensorless motor commutation and becomes fed back to XACTUAL. In case the motor becomes heavily loaded, VDCMIN also is used as the minimum step velocity. Activate stop on stall (sg_stop) to detect step loss. 0: Disable, dcStep off |VACT| = VDCMIN = 256: - Triggers the same actions as exceeding THIGH setting. - Switches on automatic commutation dcStep Hint: Also set DCCTRL parameters in order to operate dcStep. (Only bits 22… 8 are used for value and for comparison)
	#define TMC2130_VDCMIN_SHIFT                          0 // min.: 0, max.: 8388607, default: 0
	#define TMC2130_OFS0_MASK                             0x01 // MSLUT[0] // microstep table entry 0
	#define TMC2130_OFS0_SHIFT                            0 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS1_MASK                             0x02 // MSLUT[0] // microstep table entry 1
	#define TMC2130_OFS1_SHIFT                            1 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS2_MASK                             0x04 // MSLUT[0] // microstep table entry 2
	#define TMC2130_OFS2_SHIFT                            2 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS3_MASK                             0x08 // MSLUT[0] // microstep table entry 3
	#define TMC2130_OFS3_SHIFT                            3 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS4_MASK                             0x10 // MSLUT[0] // microstep table entry 4
	#define TMC2130_OFS4_SHIFT                            4 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS5_MASK                             0x20 // MSLUT[0] // microstep table entry 5
	#define TMC2130_OFS5_SHIFT                            5 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS6_MASK                             0x40 // MSLUT[0] // microstep table entry 6
	#define TMC2130_OFS6_SHIFT                            6 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS7_MASK                             0x80 // MSLUT[0] // microstep table entry 7
	#define TMC2130_OFS7_SHIFT                            7 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS8_MASK                             0x0100 // MSLUT[0] // microstep table entry 8
	#define TMC2130_OFS8_SHIFT                            8 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS9_MASK                             0x0200 // MSLUT[0] // microstep table entry 9
	#define TMC2130_OFS9_SHIFT                            9 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS10_MASK                            0x0400 // MSLUT[0] // microstep table entry 10
	#define TMC2130_OFS10_SHIFT                           10 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS11_MASK                            0x0800 // MSLUT[0] // microstep table entry 11
	#define TMC2130_OFS11_SHIFT                           11 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS12_MASK                            0x1000 // MSLUT[0] // microstep table entry 12
	#define TMC2130_OFS12_SHIFT                           12 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS13_MASK                            0x2000 // MSLUT[0] // microstep table entry 13
	#define TMC2130_OFS13_SHIFT                           13 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS14_MASK                            0x4000 // MSLUT[0] // microstep table entry 14
	#define TMC2130_OFS14_SHIFT                           14 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS15_MASK                            0x8000 // MSLUT[0] // microstep table entry 15
	#define TMC2130_OFS15_SHIFT                           15 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS16_MASK                            0x010000 // MSLUT[0] // microstep table entry 16
	#define TMC2130_OFS16_SHIFT                           16 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS17_MASK                            0x020000 // MSLUT[0] // microstep table entry 17
	#define TMC2130_OFS17_SHIFT                           17 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS18_MASK                            0x040000 // MSLUT[0] // microstep table entry 18
	#define TMC2130_OFS18_SHIFT                           18 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS19_MASK                            0x080000 // MSLUT[0] // microstep table entry 19
	#define TMC2130_OFS19_SHIFT                           19 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS20_MASK                            0x100000 // MSLUT[0] // microstep table entry 20
	#define TMC2130_OFS20_SHIFT                           20 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS21_MASK                            0x200000 // MSLUT[0] // microstep table entry 21
	#define TMC2130_OFS21_SHIFT                           21 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS22_MASK                            0x400000 // MSLUT[0] // microstep table entry 22
	#define TMC2130_OFS22_SHIFT                           22 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS23_MASK                            0x800000 // MSLUT[0] // microstep table entry 23
	#define TMC2130_OFS23_SHIFT                           23 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS24_MASK                            0x01000000 // MSLUT[0] // microstep table entry 24
	#define TMC2130_OFS24_SHIFT                           24 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS25_MASK                            0x02000000 // MSLUT[0] // microstep table entry 25
	#define TMC2130_OFS25_SHIFT                           25 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS26_MASK                            0x04000000 // MSLUT[0] // microstep table entry 26
	#define TMC2130_OFS26_SHIFT                           26 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS27_MASK                            0x08000000 // MSLUT[0] // microstep table entry 27
	#define TMC2130_OFS27_SHIFT                           27 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS28_MASK                            0x10000000 // MSLUT[0] // microstep table entry 28
	#define TMC2130_OFS28_SHIFT                           28 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS29_MASK                            0x20000000 // MSLUT[0] // microstep table entry 29
	#define TMC2130_OFS29_SHIFT                           29 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS30_MASK                            0x40000000 // MSLUT[0] // microstep table entry 30
	#define TMC2130_OFS30_SHIFT                           30 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS31_MASK                            0x80000000 // MSLUT[0] // microstep table entry 31
	#define TMC2130_OFS31_SHIFT                           31 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS32_MASK                            0x01 // MSLUT[1] // microstep table entry 32
	#define TMC2130_OFS32_SHIFT                           0 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS33_MASK                            0x02 // MSLUT[1] // microstep table entry 33
	#define TMC2130_OFS33_SHIFT                           1 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS34_MASK                            0x04 // MSLUT[1] // microstep table entry 34
	#define TMC2130_OFS34_SHIFT                           2 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS35_MASK                            0x08 // MSLUT[1] // microstep table entry 35
	#define TMC2130_OFS35_SHIFT                           3 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS36_MASK                            0x10 // MSLUT[1] // microstep table entry 36
	#define TMC2130_OFS36_SHIFT                           4 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS37_MASK                            0x20 // MSLUT[1] // microstep table entry 37
	#define TMC2130_OFS37_SHIFT                           5 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS38_MASK                            0x40 // MSLUT[1] // microstep table entry 38
	#define TMC2130_OFS38_SHIFT                           6 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS39_MASK                            0x80 // MSLUT[1] // microstep table entry 39
	#define TMC2130_OFS39_SHIFT                           7 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS40_MASK                            0x0100 // MSLUT[1] // microstep table entry 40
	#define TMC2130_OFS40_SHIFT                           8 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS41_MASK                            0x0200 // MSLUT[1] // microstep table entry 41
	#define TMC2130_OFS41_SHIFT                           9 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS42_MASK                            0x0400 // MSLUT[1] // microstep table entry 42
	#define TMC2130_OFS42_SHIFT                           10 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS43_MASK                            0x0800 // MSLUT[1] // microstep table entry 43
	#define TMC2130_OFS43_SHIFT                           11 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS44_MASK                            0x1000 // MSLUT[1] // microstep table entry 44
	#define TMC2130_OFS44_SHIFT                           12 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS45_MASK                            0x2000 // MSLUT[1] // microstep table entry 45
	#define TMC2130_OFS45_SHIFT                           13 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS46_MASK                            0x4000 // MSLUT[1] // microstep table entry 46
	#define TMC2130_OFS46_SHIFT                           14 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS47_MASK                            0x8000 // MSLUT[1] // microstep table entry 47
	#define TMC2130_OFS47_SHIFT                           15 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS48_MASK                            0x010000 // MSLUT[1] // microstep table entry 48
	#define TMC2130_OFS48_SHIFT                           16 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS49_MASK                            0x020000 // MSLUT[1] // microstep table entry 49
	#define TMC2130_OFS49_SHIFT                           17 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS50_MASK                            0x040000 // MSLUT[1] // microstep table entry 50
	#define TMC2130_OFS50_SHIFT                           18 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS51_MASK                            0x080000 // MSLUT[1] // microstep table entry 51
	#define TMC2130_OFS51_SHIFT                           19 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS52_MASK                            0x100000 // MSLUT[1] // microstep table entry 52
	#define TMC2130_OFS52_SHIFT                           20 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS53_MASK                            0x200000 // MSLUT[1] // microstep table entry 53
	#define TMC2130_OFS53_SHIFT                           21 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS54_MASK                            0x400000 // MSLUT[1] // microstep table entry 54
	#define TMC2130_OFS54_SHIFT                           22 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS55_MASK                            0x800000 // MSLUT[1] // microstep table entry 55
	#define TMC2130_OFS55_SHIFT                           23 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS56_MASK                            0x01000000 // MSLUT[1] // microstep table entry 56
	#define TMC2130_OFS56_SHIFT                           24 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS57_MASK                            0x02000000 // MSLUT[1] // microstep table entry 57
	#define TMC2130_OFS57_SHIFT                           25 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS58_MASK                            0x04000000 // MSLUT[1] // microstep table entry 58
	#define TMC2130_OFS58_SHIFT                           26 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS59_MASK                            0x08000000 // MSLUT[1] // microstep table entry 59
	#define TMC2130_OFS59_SHIFT                           27 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS60_MASK                            0x10000000 // MSLUT[1] // microstep table entry 60
	#define TMC2130_OFS60_SHIFT                           28 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS61_MASK                            0x20000000 // MSLUT[1] // microstep table entry 61
	#define TMC2130_OFS61_SHIFT                           29 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS62_MASK                            0x40000000 // MSLUT[1] // microstep table entry 62
	#define TMC2130_OFS62_SHIFT                           30 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS63_MASK                            0x80000000 // MSLUT[1] // microstep table entry 63
	#define TMC2130_OFS63_SHIFT                           31 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS64_MASK                            0x01 // MSLUT[2] // microstep table entry 64
	#define TMC2130_OFS64_SHIFT                           0 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS65_MASK                            0x02 // MSLUT[2] // microstep table entry 65
	#define TMC2130_OFS65_SHIFT                           1 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS66_MASK                            0x04 // MSLUT[2] // microstep table entry 66
	#define TMC2130_OFS66_SHIFT                           2 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS67_MASK                            0x08 // MSLUT[2] // microstep table entry 67
	#define TMC2130_OFS67_SHIFT                           3 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS68_MASK                            0x10 // MSLUT[2] // microstep table entry 68
	#define TMC2130_OFS68_SHIFT                           4 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS69_MASK                            0x20 // MSLUT[2] // microstep table entry 69
	#define TMC2130_OFS69_SHIFT                           5 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS70_MASK                            0x40 // MSLUT[2] // microstep table entry 70
	#define TMC2130_OFS70_SHIFT                           6 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS71_MASK                            0x80 // MSLUT[2] // microstep table entry 71
	#define TMC2130_OFS71_SHIFT                           7 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS72_MASK                            0x0100 // MSLUT[2] // microstep table entry 72
	#define TMC2130_OFS72_SHIFT                           8 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS73_MASK                            0x0200 // MSLUT[2] // microstep table entry 73
	#define TMC2130_OFS73_SHIFT                           9 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS74_MASK                            0x0400 // MSLUT[2] // microstep table entry 74
	#define TMC2130_OFS74_SHIFT                           10 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS75_MASK                            0x0800 // MSLUT[2] // microstep table entry 75
	#define TMC2130_OFS75_SHIFT                           11 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS76_MASK                            0x1000 // MSLUT[2] // microstep table entry 76
	#define TMC2130_OFS76_SHIFT                           12 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS77_MASK                            0x2000 // MSLUT[2] // microstep table entry 77
	#define TMC2130_OFS77_SHIFT                           13 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS78_MASK                            0x4000 // MSLUT[2] // microstep table entry 78
	#define TMC2130_OFS78_SHIFT                           14 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS79_MASK                            0x8000 // MSLUT[2] // microstep table entry 79
	#define TMC2130_OFS79_SHIFT                           15 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS80_MASK                            0x010000 // MSLUT[2] // microstep table entry 80
	#define TMC2130_OFS80_SHIFT                           16 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS81_MASK                            0x020000 // MSLUT[2] // microstep table entry 81
	#define TMC2130_OFS81_SHIFT                           17 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS82_MASK                            0x040000 // MSLUT[2] // microstep table entry 82
	#define TMC2130_OFS82_SHIFT                           18 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS83_MASK                            0x080000 // MSLUT[2] // microstep table entry 83
	#define TMC2130_OFS83_SHIFT                           19 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS84_MASK                            0x100000 // MSLUT[2] // microstep table entry 84
	#define TMC2130_OFS84_SHIFT                           20 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS85_MASK                            0x200000 // MSLUT[2] // microstep table entry 85
	#define TMC2130_OFS85_SHIFT                           21 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS86_MASK                            0x400000 // MSLUT[2] // microstep table entry 86
	#define TMC2130_OFS86_SHIFT                           22 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS87_MASK                            0x800000 // MSLUT[2] // microstep table entry 87
	#define TMC2130_OFS87_SHIFT                           23 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS88_MASK                            0x01000000 // MSLUT[2] // microstep table entry 88
	#define TMC2130_OFS88_SHIFT                           24 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS89_MASK                            0x02000000 // MSLUT[2] // microstep table entry 89
	#define TMC2130_OFS89_SHIFT                           25 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS90_MASK                            0x04000000 // MSLUT[2] // microstep table entry 90
	#define TMC2130_OFS90_SHIFT                           26 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS91_MASK                            0x08000000 // MSLUT[2] // microstep table entry 91
	#define TMC2130_OFS91_SHIFT                           27 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS92_MASK                            0x10000000 // MSLUT[2] // microstep table entry 92
	#define TMC2130_OFS92_SHIFT                           28 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS93_MASK                            0x20000000 // MSLUT[2] // microstep table entry 93
	#define TMC2130_OFS93_SHIFT                           29 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS94_MASK                            0x40000000 // MSLUT[2] // microstep table entry 94
	#define TMC2130_OFS94_SHIFT                           30 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS95_MASK                            0x80000000 // MSLUT[2] // microstep table entry 95
	#define TMC2130_OFS95_SHIFT                           31 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS96_MASK                            0x01 // MSLUT[3] // microstep table entry 96
	#define TMC2130_OFS96_SHIFT                           0 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS97_MASK                            0x02 // MSLUT[3] // microstep table entry 97
	#define TMC2130_OFS97_SHIFT                           1 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS98_MASK                            0x04 // MSLUT[3] // microstep table entry 98
	#define TMC2130_OFS98_SHIFT                           2 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS99_MASK                            0x08 // MSLUT[3] // microstep table entry 99
	#define TMC2130_OFS99_SHIFT                           3 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS100_MASK                           0x10 // MSLUT[3] // microstep table entry 100
	#define TMC2130_OFS100_SHIFT                          4 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS101_MASK                           0x20 // MSLUT[3] // microstep table entry 101
	#define TMC2130_OFS101_SHIFT                          5 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS102_MASK                           0x40 // MSLUT[3] // microstep table entry 102
	#define TMC2130_OFS102_SHIFT                          6 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS103_MASK                           0x80 // MSLUT[3] // microstep table entry 103
	#define TMC2130_OFS103_SHIFT                          7 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS104_MASK                           0x0100 // MSLUT[3] // microstep table entry 104
	#define TMC2130_OFS104_SHIFT                          8 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS105_MASK                           0x0200 // MSLUT[3] // microstep table entry 105
	#define TMC2130_OFS105_SHIFT                          9 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS106_MASK                           0x0400 // MSLUT[3] // microstep table entry 106
	#define TMC2130_OFS106_SHIFT                          10 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS107_MASK                           0x0800 // MSLUT[3] // microstep table entry 107
	#define TMC2130_OFS107_SHIFT                          11 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS108_MASK                           0x1000 // MSLUT[3] // microstep table entry 108
	#define TMC2130_OFS108_SHIFT                          12 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS109_MASK                           0x2000 // MSLUT[3] // microstep table entry 109
	#define TMC2130_OFS109_SHIFT                          13 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS110_MASK                           0x4000 // MSLUT[3] // microstep table entry 110
	#define TMC2130_OFS110_SHIFT                          14 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS111_MASK                           0x8000 // MSLUT[3] // microstep table entry 111
	#define TMC2130_OFS111_SHIFT                          15 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS112_MASK                           0x010000 // MSLUT[3] // microstep table entry 112
	#define TMC2130_OFS112_SHIFT                          16 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS113_MASK                           0x020000 // MSLUT[3] // microstep table entry 113
	#define TMC2130_OFS113_SHIFT                          17 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS114_MASK                           0x040000 // MSLUT[3] // microstep table entry 114
	#define TMC2130_OFS114_SHIFT                          18 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS115_MASK                           0x080000 // MSLUT[3] // microstep table entry 115
	#define TMC2130_OFS115_SHIFT                          19 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS116_MASK                           0x100000 // MSLUT[3] // microstep table entry 116
	#define TMC2130_OFS116_SHIFT                          20 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS117_MASK                           0x200000 // MSLUT[3] // microstep table entry 117
	#define TMC2130_OFS117_SHIFT                          21 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS118_MASK                           0x400000 // MSLUT[3] // microstep table entry 118
	#define TMC2130_OFS118_SHIFT                          22 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS119_MASK                           0x800000 // MSLUT[3] // microstep table entry 119
	#define TMC2130_OFS119_SHIFT                          23 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS120_MASK                           0x01000000 // MSLUT[3] // microstep table entry 120
	#define TMC2130_OFS120_SHIFT                          24 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS121_MASK                           0x02000000 // MSLUT[3] // microstep table entry 121
	#define TMC2130_OFS121_SHIFT                          25 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS122_MASK                           0x04000000 // MSLUT[3] // microstep table entry 122
	#define TMC2130_OFS122_SHIFT                          26 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS123_MASK                           0x08000000 // MSLUT[3] // microstep table entry 123
	#define TMC2130_OFS123_SHIFT                          27 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS124_MASK                           0x10000000 // MSLUT[3] // microstep table entry 124
	#define TMC2130_OFS124_SHIFT                          28 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS125_MASK                           0x20000000 // MSLUT[3] // microstep table entry 125
	#define TMC2130_OFS125_SHIFT                          29 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS126_MASK                           0x40000000 // MSLUT[3] // microstep table entry 126
	#define TMC2130_OFS126_SHIFT                          30 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS127_MASK                           0x80000000 // MSLUT[3] // microstep table entry 127
	#define TMC2130_OFS127_SHIFT                          31 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS128_MASK                           0x01 // MSLUT[4] // microstep table entry 128
	#define TMC2130_OFS128_SHIFT                          0 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS129_MASK                           0x02 // MSLUT[4] // microstep table entry 129
	#define TMC2130_OFS129_SHIFT                          1 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS130_MASK                           0x04 // MSLUT[4] // microstep table entry 130
	#define TMC2130_OFS130_SHIFT                          2 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS131_MASK                           0x08 // MSLUT[4] // microstep table entry 131
	#define TMC2130_OFS131_SHIFT                          3 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS132_MASK                           0x10 // MSLUT[4] // microstep table entry 132
	#define TMC2130_OFS132_SHIFT                          4 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS133_MASK                           0x20 // MSLUT[4] // microstep table entry 133
	#define TMC2130_OFS133_SHIFT                          5 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS134_MASK                           0x40 // MSLUT[4] // microstep table entry 134
	#define TMC2130_OFS134_SHIFT                          6 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS135_MASK                           0x80 // MSLUT[4] // microstep table entry 135
	#define TMC2130_OFS135_SHIFT                          7 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS136_MASK                           0x0100 // MSLUT[4] // microstep table entry 136
	#define TMC2130_OFS136_SHIFT                          8 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS137_MASK                           0x0200 // MSLUT[4] // microstep table entry 137
	#define TMC2130_OFS137_SHIFT                          9 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS138_MASK                           0x0400 // MSLUT[4] // microstep table entry 138
	#define TMC2130_OFS138_SHIFT                          10 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS139_MASK                           0x0800 // MSLUT[4] // microstep table entry 139
	#define TMC2130_OFS139_SHIFT                          11 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS140_MASK                           0x1000 // MSLUT[4] // microstep table entry 140
	#define TMC2130_OFS140_SHIFT                          12 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS141_MASK                           0x2000 // MSLUT[4] // microstep table entry 141
	#define TMC2130_OFS141_SHIFT                          13 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS142_MASK                           0x4000 // MSLUT[4] // microstep table entry 142
	#define TMC2130_OFS142_SHIFT                          14 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS143_MASK                           0x8000 // MSLUT[4] // microstep table entry 143
	#define TMC2130_OFS143_SHIFT                          15 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS144_MASK                           0x010000 // MSLUT[4] // microstep table entry 144
	#define TMC2130_OFS144_SHIFT                          16 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS145_MASK                           0x020000 // MSLUT[4] // microstep table entry 145
	#define TMC2130_OFS145_SHIFT                          17 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS146_MASK                           0x040000 // MSLUT[4] // microstep table entry 146
	#define TMC2130_OFS146_SHIFT                          18 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS147_MASK                           0x080000 // MSLUT[4] // microstep table entry 147
	#define TMC2130_OFS147_SHIFT                          19 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS148_MASK                           0x100000 // MSLUT[4] // microstep table entry 148
	#define TMC2130_OFS148_SHIFT                          20 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS149_MASK                           0x200000 // MSLUT[4] // microstep table entry 149
	#define TMC2130_OFS149_SHIFT                          21 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS150_MASK                           0x400000 // MSLUT[4] // microstep table entry 150
	#define TMC2130_OFS150_SHIFT                          22 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS151_MASK                           0x800000 // MSLUT[4] // microstep table entry 151
	#define TMC2130_OFS151_SHIFT                          23 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS152_MASK                           0x01000000 // MSLUT[4] // microstep table entry 152
	#define TMC2130_OFS152_SHIFT                          24 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS153_MASK                           0x02000000 // MSLUT[4] // microstep table entry 153
	#define TMC2130_OFS153_SHIFT                          25 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS154_MASK                           0x04000000 // MSLUT[4] // microstep table entry 154
	#define TMC2130_OFS154_SHIFT                          26 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS155_MASK                           0x08000000 // MSLUT[4] // microstep table entry 155
	#define TMC2130_OFS155_SHIFT                          27 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS156_MASK                           0x10000000 // MSLUT[4] // microstep table entry 156
	#define TMC2130_OFS156_SHIFT                          28 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS157_MASK                           0x20000000 // MSLUT[4] // microstep table entry 157
	#define TMC2130_OFS157_SHIFT                          29 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS158_MASK                           0x40000000 // MSLUT[4] // microstep table entry 158
	#define TMC2130_OFS158_SHIFT                          30 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS159_MASK                           0x80000000 // MSLUT[4] // microstep table entry 159
	#define TMC2130_OFS159_SHIFT                          31 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS160_MASK                           0x01 // MSLUT[5] // microstep table entry 160
	#define TMC2130_OFS160_SHIFT                          0 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS161_MASK                           0x02 // MSLUT[5] // microstep table entry 161
	#define TMC2130_OFS161_SHIFT                          1 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS162_MASK                           0x04 // MSLUT[5] // microstep table entry 162
	#define TMC2130_OFS162_SHIFT                          2 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS163_MASK                           0x08 // MSLUT[5] // microstep table entry 163
	#define TMC2130_OFS163_SHIFT                          3 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS164_MASK                           0x10 // MSLUT[5] // microstep table entry 164
	#define TMC2130_OFS164_SHIFT                          4 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS165_MASK                           0x20 // MSLUT[5] // microstep table entry 165
	#define TMC2130_OFS165_SHIFT                          5 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS166_MASK                           0x40 // MSLUT[5] // microstep table entry 166
	#define TMC2130_OFS166_SHIFT                          6 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS167_MASK                           0x80 // MSLUT[5] // microstep table entry 167
	#define TMC2130_OFS167_SHIFT                          7 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS168_MASK                           0x0100 // MSLUT[5] // microstep table entry 168
	#define TMC2130_OFS168_SHIFT                          8 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS169_MASK                           0x0200 // MSLUT[5] // microstep table entry 169
	#define TMC2130_OFS169_SHIFT                          9 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS170_MASK                           0x0400 // MSLUT[5] // microstep table entry 170
	#define TMC2130_OFS170_SHIFT                          10 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS171_MASK                           0x0800 // MSLUT[5] // microstep table entry 171
	#define TMC2130_OFS171_SHIFT                          11 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS172_MASK                           0x1000 // MSLUT[5] // microstep table entry 172
	#define TMC2130_OFS172_SHIFT                          12 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS173_MASK                           0x2000 // MSLUT[5] // microstep table entry 173
	#define TMC2130_OFS173_SHIFT                          13 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS174_MASK                           0x4000 // MSLUT[5] // microstep table entry 174
	#define TMC2130_OFS174_SHIFT                          14 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS175_MASK                           0x8000 // MSLUT[5] // microstep table entry 175
	#define TMC2130_OFS175_SHIFT                          15 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS176_MASK                           0x010000 // MSLUT[5] // microstep table entry 176
	#define TMC2130_OFS176_SHIFT                          16 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS177_MASK                           0x020000 // MSLUT[5] // microstep table entry 177
	#define TMC2130_OFS177_SHIFT                          17 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS178_MASK                           0x040000 // MSLUT[5] // microstep table entry 178
	#define TMC2130_OFS178_SHIFT                          18 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS179_MASK                           0x080000 // MSLUT[5] // microstep table entry 179
	#define TMC2130_OFS179_SHIFT                          19 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS180_MASK                           0x100000 // MSLUT[5] // microstep table entry 180
	#define TMC2130_OFS180_SHIFT                          20 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS181_MASK                           0x200000 // MSLUT[5] // microstep table entry 181
	#define TMC2130_OFS181_SHIFT                          21 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS182_MASK                           0x400000 // MSLUT[5] // microstep table entry 182
	#define TMC2130_OFS182_SHIFT                          22 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS183_MASK                           0x800000 // MSLUT[5] // microstep table entry 183
	#define TMC2130_OFS183_SHIFT                          23 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS184_MASK                           0x01000000 // MSLUT[5] // microstep table entry 184
	#define TMC2130_OFS184_SHIFT                          24 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS185_MASK                           0x02000000 // MSLUT[5] // microstep table entry 185
	#define TMC2130_OFS185_SHIFT                          25 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS186_MASK                           0x04000000 // MSLUT[5] // microstep table entry 186
	#define TMC2130_OFS186_SHIFT                          26 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS187_MASK                           0x08000000 // MSLUT[5] // microstep table entry 187
	#define TMC2130_OFS187_SHIFT                          27 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS188_MASK                           0x10000000 // MSLUT[5] // microstep table entry 188
	#define TMC2130_OFS188_SHIFT                          28 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS189_MASK                           0x20000000 // MSLUT[5] // microstep table entry 189
	#define TMC2130_OFS189_SHIFT                          29 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS190_MASK                           0x40000000 // MSLUT[5] // microstep table entry 190
	#define TMC2130_OFS190_SHIFT                          30 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS191_MASK                           0x80000000 // MSLUT[5] // microstep table entry 191
	#define TMC2130_OFS191_SHIFT                          31 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS192_MASK                           0x01 // MSLUT[6] // microstep table entry 192
	#define TMC2130_OFS192_SHIFT                          0 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS193_MASK                           0x02 // MSLUT[6] // microstep table entry 193
	#define TMC2130_OFS193_SHIFT                          1 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS194_MASK                           0x04 // MSLUT[6] // microstep table entry 194
	#define TMC2130_OFS194_SHIFT                          2 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS195_MASK                           0x08 // MSLUT[6] // microstep table entry 195
	#define TMC2130_OFS195_SHIFT                          3 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS196_MASK                           0x10 // MSLUT[6] // microstep table entry 196
	#define TMC2130_OFS196_SHIFT                          4 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS197_MASK                           0x20 // MSLUT[6] // microstep table entry 197
	#define TMC2130_OFS197_SHIFT                          5 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS198_MASK                           0x40 // MSLUT[6] // microstep table entry 198
	#define TMC2130_OFS198_SHIFT                          6 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS199_MASK                           0x80 // MSLUT[6] // microstep table entry 199
	#define TMC2130_OFS199_SHIFT                          7 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS200_MASK                           0x0100 // MSLUT[6] // microstep table entry 200
	#define TMC2130_OFS200_SHIFT                          8 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS201_MASK                           0x0200 // MSLUT[6] // microstep table entry 201
	#define TMC2130_OFS201_SHIFT                          9 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS202_MASK                           0x0400 // MSLUT[6] // microstep table entry 202
	#define TMC2130_OFS202_SHIFT                          10 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS203_MASK                           0x0800 // MSLUT[6] // microstep table entry 203
	#define TMC2130_OFS203_SHIFT                          11 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS204_MASK                           0x1000 // MSLUT[6] // microstep table entry 204
	#define TMC2130_OFS204_SHIFT                          12 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS205_MASK                           0x2000 // MSLUT[6] // microstep table entry 205
	#define TMC2130_OFS205_SHIFT                          13 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS206_MASK                           0x4000 // MSLUT[6] // microstep table entry 206
	#define TMC2130_OFS206_SHIFT                          14 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS207_MASK                           0x8000 // MSLUT[6] // microstep table entry 207
	#define TMC2130_OFS207_SHIFT                          15 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS208_MASK                           0x010000 // MSLUT[6] // microstep table entry 208
	#define TMC2130_OFS208_SHIFT                          16 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS209_MASK                           0x020000 // MSLUT[6] // microstep table entry 209
	#define TMC2130_OFS209_SHIFT                          17 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS210_MASK                           0x040000 // MSLUT[6] // microstep table entry 210
	#define TMC2130_OFS210_SHIFT                          18 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS211_MASK                           0x080000 // MSLUT[6] // microstep table entry 211
	#define TMC2130_OFS211_SHIFT                          19 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS212_MASK                           0x100000 // MSLUT[6] // microstep table entry 212
	#define TMC2130_OFS212_SHIFT                          20 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS213_MASK                           0x200000 // MSLUT[6] // microstep table entry 213
	#define TMC2130_OFS213_SHIFT                          21 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS214_MASK                           0x400000 // MSLUT[6] // microstep table entry 214
	#define TMC2130_OFS214_SHIFT                          22 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS215_MASK                           0x800000 // MSLUT[6] // microstep table entry 215
	#define TMC2130_OFS215_SHIFT                          23 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS216_MASK                           0x01000000 // MSLUT[6] // microstep table entry 216
	#define TMC2130_OFS216_SHIFT                          24 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS217_MASK                           0x02000000 // MSLUT[6] // microstep table entry 217
	#define TMC2130_OFS217_SHIFT                          25 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS218_MASK                           0x04000000 // MSLUT[6] // microstep table entry 218
	#define TMC2130_OFS218_SHIFT                          26 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS219_MASK                           0x08000000 // MSLUT[6] // microstep table entry 219
	#define TMC2130_OFS219_SHIFT                          27 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS220_MASK                           0x10000000 // MSLUT[6] // microstep table entry 220
	#define TMC2130_OFS220_SHIFT                          28 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS221_MASK                           0x20000000 // MSLUT[6] // microstep table entry 221
	#define TMC2130_OFS221_SHIFT                          29 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS222_MASK                           0x40000000 // MSLUT[6] // microstep table entry 222
	#define TMC2130_OFS222_SHIFT                          30 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS223_MASK                           0x80000000 // MSLUT[6] // microstep table entry 223
	#define TMC2130_OFS223_SHIFT                          31 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS224_MASK                           0x01 // MSLUT[7] // microstep table entry 224
	#define TMC2130_OFS224_SHIFT                          0 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS225_MASK                           0x02 // MSLUT[7] // microstep table entry 225
	#define TMC2130_OFS225_SHIFT                          1 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS226_MASK                           0x04 // MSLUT[7] // microstep table entry 226
	#define TMC2130_OFS226_SHIFT                          2 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS227_MASK                           0x08 // MSLUT[7] // microstep table entry 227
	#define TMC2130_OFS227_SHIFT                          3 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS228_MASK                           0x10 // MSLUT[7] // microstep table entry 228
	#define TMC2130_OFS228_SHIFT                          4 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS229_MASK                           0x20 // MSLUT[7] // microstep table entry 229
	#define TMC2130_OFS229_SHIFT                          5 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS230_MASK                           0x40 // MSLUT[7] // microstep table entry 230
	#define TMC2130_OFS230_SHIFT                          6 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS231_MASK                           0x80 // MSLUT[7] // microstep table entry 231
	#define TMC2130_OFS231_SHIFT                          7 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS232_MASK                           0x0100 // MSLUT[7] // microstep table entry 232
	#define TMC2130_OFS232_SHIFT                          8 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS233_MASK                           0x0200 // MSLUT[7] // microstep table entry 233
	#define TMC2130_OFS233_SHIFT                          9 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS234_MASK                           0x0400 // MSLUT[7] // microstep table entry 234
	#define TMC2130_OFS234_SHIFT                          10 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS235_MASK                           0x0800 // MSLUT[7] // microstep table entry 235
	#define TMC2130_OFS235_SHIFT                          11 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS236_MASK                           0x1000 // MSLUT[7] // microstep table entry 236
	#define TMC2130_OFS236_SHIFT                          12 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS237_MASK                           0x2000 // MSLUT[7] // microstep table entry 237
	#define TMC2130_OFS237_SHIFT                          13 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS238_MASK                           0x4000 // MSLUT[7] // microstep table entry 238
	#define TMC2130_OFS238_SHIFT                          14 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS239_MASK                           0x8000 // MSLUT[7] // microstep table entry 239
	#define TMC2130_OFS239_SHIFT                          15 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS240_MASK                           0x010000 // MSLUT[7] // microstep table entry 240
	#define TMC2130_OFS240_SHIFT                          16 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS241_MASK                           0x020000 // MSLUT[7] // microstep table entry 241
	#define TMC2130_OFS241_SHIFT                          17 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS242_MASK                           0x040000 // MSLUT[7] // microstep table entry 242
	#define TMC2130_OFS242_SHIFT                          18 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS243_MASK                           0x080000 // MSLUT[7] // microstep table entry 243
	#define TMC2130_OFS243_SHIFT                          19 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS244_MASK                           0x100000 // MSLUT[7] // microstep table entry 244
	#define TMC2130_OFS244_SHIFT                          20 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS245_MASK                           0x200000 // MSLUT[7] // microstep table entry 245
	#define TMC2130_OFS245_SHIFT                          21 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS246_MASK                           0x400000 // MSLUT[7] // microstep table entry 246
	#define TMC2130_OFS246_SHIFT                          22 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS247_MASK                           0x800000 // MSLUT[7] // microstep table entry 247
	#define TMC2130_OFS247_SHIFT                          23 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS248_MASK                           0x01000000 // MSLUT[7] // microstep table entry 248
	#define TMC2130_OFS248_SHIFT                          24 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS249_MASK                           0x02000000 // MSLUT[7] // microstep table entry 249
	#define TMC2130_OFS249_SHIFT                          25 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS250_MASK                           0x04000000 // MSLUT[7] // microstep table entry 250
	#define TMC2130_OFS250_SHIFT                          26 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS251_MASK                           0x08000000 // MSLUT[7] // microstep table entry 251
	#define TMC2130_OFS251_SHIFT                          27 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS252_MASK                           0x10000000 // MSLUT[7] // microstep table entry 252
	#define TMC2130_OFS252_SHIFT                          28 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS253_MASK                           0x20000000 // MSLUT[7] // microstep table entry 253
	#define TMC2130_OFS253_SHIFT                          29 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS254_MASK                           0x40000000 // MSLUT[7] // microstep table entry 254
	#define TMC2130_OFS254_SHIFT                          30 // min.: 0, max.: 1, default: 0
	#define TMC2130_OFS255_MASK                           0x80000000 // MSLUT[7] // microstep table entry 255
	#define TMC2130_OFS255_SHIFT                          31 // min.: 0, max.: 1, default: 0
	#define TMC2130_W0_MASK                               0x03 // MSLUTSEL // LUT width select from ofs0 to ofs(X1-1)
	#define TMC2130_W0_SHIFT                              0 // min.: 0, max.: 3, default: 0
	#define TMC2130_W1_MASK                               0x0C // MSLUTSEL // LUT width select from ofs(X1) to ofs(X2-1)
	#define TMC2130_W1_SHIFT                              2 // min.: 0, max.: 3, default: 0
	#define TMC2130_W2_MASK                               0x30 // MSLUTSEL // LUT width select from ofs(X2) to ofs(X3-1)
	#define TMC2130_W2_SHIFT                              4 // min.: 0, max.: 3, default: 0
	#define TMC2130_W3_MASK                               0xC0 // MSLUTSEL // LUT width select from ofs(X3) to ofs255
	#define TMC2130_W3_SHIFT                              6 // min.: 0, max.: 3, default: 0
	#define TMC2130_X1_MASK                               0xFF00 // MSLUTSEL // LUT segment 1 start
	#define TMC2130_X1_SHIFT                              8 // min.: 0, max.: 255, default: 0
	#define TMC2130_X2_MASK                               0xFF0000 // MSLUTSEL // LUT segment 2 start
	#define TMC2130_X2_SHIFT                              16 // min.: 0, max.: 255, default: 0
	#define TMC2130_X3_MASK                               0xFF000000 // MSLUTSEL // LUT segment 3 start
	#define TMC2130_X3_SHIFT                              24 // min.: 0, max.: 255, default: 0
	#define TMC2130_START_SIN_MASK                        0xFF // MSLUTSTART // Absolute current at microstep table entry 0.
	#define TMC2130_START_SIN_SHIFT                       0 // min.: 0, max.: 255, default: 0
	#define TMC2130_START_SIN90_MASK                      0xFF0000 // MSLUTSTART // Absolute current for microstep table entry at positions 256.
	#define TMC2130_START_SIN90_SHIFT                     16 // min.: 0, max.: 255, default: 0
	#define TMC2130_MSCNT_MASK                            0x03FF // MSCNT // Microstep counter. Indicates actual position in the microstep table for CUR_A. CUR_B uses an offset of 256 (2 phase motor). Hint: Move to a position where MSCNT is zero before re-initializing MSLUTSTART or MSLUT and MSLUTSEL.
	#define TMC2130_MSCNT_SHIFT                           0 // min.: 0, max.: 1023, default: 0
	#define TMC2130_CUR_A_MASK                            0x01FF // MSCURACT // Actual microstep current for motor phase A as read from MSLUT (not scaled by current)
	#define TMC2130_CUR_A_SHIFT                           0 // min.: -256, max.: 255, default: 0
	#define TMC2130_CUR_B_MASK                            0x01FF0000 // MSCURACT // Actual microstep current for motor phase B as read from MSLUT (not scaled by current)
	#define TMC2130_CUR_B_SHIFT                           16 // min.: -256, max.: 255, default: 0
	#define TMC2130_TOFF_MASK                             0x0F // CHOPCONF // off time and driver enable
	#define TMC2130_TOFF_SHIFT                            0 // min.: 0, max.: 15, default: 0
	#define TMC2130_TFD_ALL_MASK                          0x70 // CHOPCONF // fast decay time setting
	#define TMC2130_TFD_ALL_SHIFT                         4 // min.: 0, max.: 7, default: 0
	#define TMC2130_OFFSET_MASK                           0x0780 // CHOPCONF // sine wave offset
	#define TMC2130_OFFSET_SHIFT                          7 // min.: 0, max.: 15, default: 0
	#define TMC2130_TFD_3_MASK                            0x0800 // CHOPCONF // MSB of fast decay time setting
	#define TMC2130_TFD_3_SHIFT                           11 // min.: 0, max.: 1, default: 0
	#define TMC2130_DISFDCC_MASK                          0x1000 // CHOPCONF // fast decay mode
	#define TMC2130_DISFDCC_SHIFT                         12 // min.: 0, max.: 1, default: 0
	#define TMC2130_RNDTF_MASK                            0x2000 // CHOPCONF // random TOFF time
	#define TMC2130_RNDTF_SHIFT                           13 // min.: 0, max.: 1, default: 0
	#define TMC2130_CHM_MASK                              0x4000 // CHOPCONF // chopper mode
	#define TMC2130_CHM_SHIFT                             14 // min.: 0, max.: 1, default: 0
	#define TMC2130_TBL_MASK                              0x018000 // CHOPCONF // blank time select
	#define TMC2130_TBL_SHIFT                             15 // min.: 0, max.: 3, default: 0
	#define TMC2130_VSENSE_MASK                           0x020000 // CHOPCONF // sense resistor voltage based current scaling
	#define TMC2130_VSENSE_SHIFT                          17 // min.: 0, max.: 1, default: 0
	#define TMC2130_VHIGHFS_MASK                          0x040000 // CHOPCONF // high velocity fullstep selection
	#define TMC2130_VHIGHFS_SHIFT                         18 // min.: 0, max.: 1, default: 0
	#define TMC2130_VHIGHCHM_MASK                         0x080000 // CHOPCONF // high velocity chopper mode
	#define TMC2130_VHIGHCHM_SHIFT                        19 // min.: 0, max.: 1, default: 0
	#define TMC2130_SYNC_MASK                             0xF00000 // CHOPCONF // PWM synchronization clock
	#define TMC2130_SYNC_SHIFT                            20 // min.: 0, max.: 15, default: 0
	#define TMC2130_MRES_MASK                             0x0F000000 // CHOPCONF // Micro step resolution; The resolution gives the number of microstep entries per sine quarter wave. The driver automatically uses microstep positions which result in a symmetrical wave, when choosing a lower microstep resolution.
	#define TMC2130_MRES_SHIFT                            24 // min.: 0, max.: 8, default: 0
	#define TMC2130_INTPOL_MASK                           0x10000000 // CHOPCONF // interpolation to 256 microsteps
	#define TMC2130_INTPOL_SHIFT                          28 // min.: 0, max.: 1, default: 0
	#define TMC2130_DEDGE_MASK                            0x20000000 // CHOPCONF // enable double edge step pulses
	#define TMC2130_DEDGE_SHIFT                           29 // min.: 0, max.: 1, default: 0
	#define TMC2130_DISS2G_MASK                           0x40000000 // CHOPCONF // short to GND protection disable
	#define TMC2130_DISS2G_SHIFT                          30 // min.: 0, max.: 1, default: 0
	#define TMC2130_TOFF_MASK                             0x0F // CHOPCONF // off time and driver enable
	#define TMC2130_TOFF_SHIFT                            0 // min.: 0, max.: 15, default: 0
	#define TMC2130_TFD_ALL_MASK                          0x70 // CHOPCONF // fast decay time setting
	#define TMC2130_TFD_ALL_SHIFT                         4 // min.: 0, max.: 7, default: 0
	#define TMC2130_OFFSET_MASK                           0x0780 // CHOPCONF // sine wave offset
	#define TMC2130_OFFSET_SHIFT                          7 // min.: 0, max.: 15, default: 0
	#define TMC2130_TFD_3_MASK                            0x0800 // CHOPCONF // MSB of fast decay time setting
	#define TMC2130_TFD_3_SHIFT                           11 // min.: 0, max.: 1, default: 0
	#define TMC2130_DISFDCC_MASK                          0x1000 // CHOPCONF // fast decay mode
	#define TMC2130_DISFDCC_SHIFT                         12 // min.: 0, max.: 1, default: 0
	#define TMC2130_RNDTF_MASK                            0x2000 // CHOPCONF // random TOFF time
	#define TMC2130_RNDTF_SHIFT                           13 // min.: 0, max.: 1, default: 0
	#define TMC2130_CHM_MASK                              0x4000 // CHOPCONF // chopper mode
	#define TMC2130_CHM_SHIFT                             14 // min.: 0, max.: 1, default: 0
	#define TMC2130_TBL_MASK                              0x018000 // CHOPCONF // blank time select
	#define TMC2130_TBL_SHIFT                             15 // min.: 0, max.: 3, default: 0
	#define TMC2130_VSENSE_MASK                           0x020000 // CHOPCONF // sense resistor voltage based current scaling
	#define TMC2130_VSENSE_SHIFT                          17 // min.: 0, max.: 1, default: 0
	#define TMC2130_VHIGHFS_MASK                          0x040000 // CHOPCONF // high velocity fullstep selection
	#define TMC2130_VHIGHFS_SHIFT                         18 // min.: 0, max.: 1, default: 0
	#define TMC2130_VHIGHCHM_MASK                         0x080000 // CHOPCONF // high velocity chopper mode
	#define TMC2130_VHIGHCHM_SHIFT                        19 // min.: 0, max.: 1, default: 0
	#define TMC2130_SYNC_MASK                             0xF00000 // CHOPCONF // PWM synchronization clock
	#define TMC2130_SYNC_SHIFT                            20 // min.: 0, max.: 15, default: 0
	#define TMC2130_MRES_MASK                             0x0F000000 // CHOPCONF // Micro step resolution; The resolution gives the number of microstep entries per sine quarter wave. The driver automatically uses microstep positions which result in a symmetrical wave, when choosing a lower microstep resolution.
	#define TMC2130_MRES_SHIFT                            24 // min.: 0, max.: 8, default: 0
	#define TMC2130_INTPOL_MASK                           0x10000000 // CHOPCONF // interpolation to 256 microsteps
	#define TMC2130_INTPOL_SHIFT                          28 // min.: 0, max.: 1, default: 0
	#define TMC2130_DEDGE_MASK                            0x20000000 // CHOPCONF // enable double edge step pulses
	#define TMC2130_DEDGE_SHIFT                           29 // min.: 0, max.: 1, default: 0
	#define TMC2130_DISS2G_MASK                           0x40000000 // CHOPCONF // short to GND protection disable
	#define TMC2130_DISS2G_SHIFT                          30 // min.: 0, max.: 1, default: 0
	#define TMC2130_TOFF_MASK                             0x0F // CHOPCONF // off time and driver enable
	#define TMC2130_TOFF_SHIFT                            0 // min.: 0, max.: 15, default: 0
	#define TMC2130_HSTRT_MASK                            0x70 // CHOPCONF // hysteresis start value added to HEND; Attention: Effective HEND+HSTRT less than or equal to 16. Hint: Hysteresis decrement is done each 16 clocks
	#define TMC2130_HSTRT_SHIFT                           4 // min.: 0, max.: 7, default: 0
	#define TMC2130_HEND_MASK                             0x0780 // CHOPCONF // hysteresis low value
	#define TMC2130_HEND_SHIFT                            7 // min.: 0, max.: 15, default: 0
	#define TMC2130_RNDTF_MASK                            0x2000 // CHOPCONF // random TOFF time
	#define TMC2130_RNDTF_SHIFT                           13 // min.: 0, max.: 1, default: 0
	#define TMC2130_CHM_MASK                              0x4000 // CHOPCONF // chopper mode
	#define TMC2130_CHM_SHIFT                             14 // min.: 0, max.: 1, default: 0
	#define TMC2130_TBL_MASK                              0x018000 // CHOPCONF // blank time select
	#define TMC2130_TBL_SHIFT                             15 // min.: 0, max.: 3, default: 0
	#define TMC2130_VSENSE_MASK                           0x020000 // CHOPCONF // sense resistor voltage based current scaling
	#define TMC2130_VSENSE_SHIFT                          17 // min.: 0, max.: 1, default: 0
	#define TMC2130_VHIGHFS_MASK                          0x040000 // CHOPCONF // high velocity fullstep selection
	#define TMC2130_VHIGHFS_SHIFT                         18 // min.: 0, max.: 1, default: 0
	#define TMC2130_VHIGHCHM_MASK                         0x080000 // CHOPCONF // high velocity chopper mode
	#define TMC2130_VHIGHCHM_SHIFT                        19 // min.: 0, max.: 1, default: 0
	#define TMC2130_SYNC_MASK                             0xF00000 // CHOPCONF // PWM synchronization clock
	#define TMC2130_SYNC_SHIFT                            20 // min.: 0, max.: 15, default: 0
	#define TMC2130_MRES_MASK                             0x0F000000 // CHOPCONF // Micro step resolution; The resolution gives the number of microstep entries per sine quarter wave. The driver automatically uses microstep positions which result in a symmetrical wave, when choosing a lower microstep resolution.
	#define TMC2130_MRES_SHIFT                            24 // min.: 0, max.: 8, default: 0
	#define TMC2130_INTPOL_MASK                           0x10000000 // CHOPCONF // interpolation to 256 microsteps
	#define TMC2130_INTPOL_SHIFT                          28 // min.: 0, max.: 1, default: 0
	#define TMC2130_DEDGE_MASK                            0x20000000 // CHOPCONF // enable double edge step pulses
	#define TMC2130_DEDGE_SHIFT                           29 // min.: 0, max.: 1, default: 0
	#define TMC2130_DISS2G_MASK                           0x40000000 // CHOPCONF // short to GND protection disable
	#define TMC2130_DISS2G_SHIFT                          30 // min.: 0, max.: 1, default: 0
	#define TMC2130_SEMIN_MASK                            0x0F // COOLCONF // minimum stallGuard2 value - If the stallGuard2 result falls below SEMIN*32, the motor current becomes increased to reduce motor load angle. 0: smart current control coolStep off
	#define TMC2130_SEMIN_SHIFT                           0 // min.: 0, max.: 15, default: 0
	#define TMC2130_SEUP_MASK                             0x60 // COOLCONF // Current increment steps per measured stallGuard2 value
	#define TMC2130_SEUP_SHIFT                            5 // min.: 0, max.: 3, default: 0
	#define TMC2130_SEMAX_MASK                            0x0F00 // COOLCONF // stallGuard2 hysteresis value - If the stallGuard2 result is equal to or above (SEMIN+SEMAX+1)*32, the motor current becomes decreased to save energy.
	#define TMC2130_SEMAX_SHIFT                           8 // min.: 0, max.: 15, default: 0
	#define TMC2130_SEDN_MASK                             0x6000 // COOLCONF // Current down step speed; For each n stallGuard2 values decrease by one
	#define TMC2130_SEDN_SHIFT                            13 // min.: 0, max.: 3, default: 0
	#define TMC2130_SEIMIN_MASK                           0x8000 // COOLCONF // minimum current for smart current control
	#define TMC2130_SEIMIN_SHIFT                          15 // min.: 0, max.: 1, default: 0
	#define TMC2130_SGT_MASK                              0x7F0000 // COOLCONF // stallGuard2 threshold value This signed value controls stallGuard2 level for stall output and sets the optimum measurement range for readout. A lower value gives a higher sensitivity. Zero is the starting value working with most motors. A higher value makes stallGuard2 less sensitive and requires more torque to indicate a stall.
	#define TMC2130_SGT_SHIFT                             16 // min.: -64, max.: 63, default: 0
	#define TMC2130_SFILT_MASK                            0x01000000 // COOLCONF // stallGuard2 filter enable
	#define TMC2130_SFILT_SHIFT                           24 // min.: 0, max.: 1, default: 0
	#define TMC2130_DC_TIME_MASK                          0x03FF // DCCTRL // Upper PWM on time limit for commutation (DC_TIME * 1/f CLK ). Set slightly above effective blank time TBL.
	#define TMC2130_DC_TIME_SHIFT                         0 // min.: 0, max.: 1023, default: 0
	#define TMC2130_DC_SG_MASK                            0xFF0000 // DCCTRL // Max. PWM on time for step loss detection using dcStep stallGuard2 in dcStep mode. (DC_SG * 16/f CLK); Set slightly higher than DC_TIME/16; 0=disable
	#define TMC2130_DC_SG_SHIFT                           16 // min.: 0, max.: 255, default: 0
	#define TMC2130_SG_RESULT_MASK                        0x03FF // DRV_STATUS // Mechanical load measurement: The stallGuard2 result gives a means to measure mechanical motor load. A higher value means lower mechanical load. A value of 0 signals highest load. With optimum SGT setting, this is an indicator for a motor stall. The stall detection compares SG_RESULT to 0 in order to detect a stall. SG_RESULT is used as a base for coolStep operation, by comparing it to a programmable upper and a lower limit. It is not applicable in stealthChop mode. SG_RESULT is ALSO applicable when dcStep is active. stallGuard2 works best with microstep operation. Temperature measurement: In standstill, no stallGuard2 result can be obtained. SG_RESULT shows the chopper on-time for motor coil A instead. If the motor is moved to a determined microstep position at a certain current setting, a comparison of the chopper on-time can help to get a rough estimation of motor temperature. As the motor heats up, its coil resistance rises and the chopper on-time increases.
	#define TMC2130_SG_RESULT_SHIFT                       0 // min.: 0, max.: 1023, default: 0
	#define TMC2130_FSACTIVE_MASK                         0x8000 // DRV_STATUS // Full step active indicator
	#define TMC2130_FSACTIVE_SHIFT                        15 // min.: 0, max.: 1, default: 0
	#define TMC2130_CS_ACTUAL_MASK                        0x1F0000 // DRV_STATUS // Actual current control scaling, for monitoring smart energy current scaling controlled via settings in register COOLCONF, or for monitoring the function of the automatic current scaling.
	#define TMC2130_CS_ACTUAL_SHIFT                       16 // min.: 0, max.: 31, default: 0
	#define TMC2130_STALLGUARD_MASK                       0x01000000 // DRV_STATUS //
	#define TMC2130_STALLGUARD_SHIFT                      24 // min.: 0, max.: 1, default: 0
	#define TMC2130_OT_MASK                               0x02000000 // DRV_STATUS //
	#define TMC2130_OT_SHIFT                              25 // min.: 0, max.: 1, default: 0
	#define TMC2130_OTPW_MASK                             0x04000000 // DRV_STATUS //
	#define TMC2130_OTPW_SHIFT                            26 // min.: 0, max.: 1, default: 0
	#define TMC2130_S2GA_MASK                             0x08000000 // DRV_STATUS //
	#define TMC2130_S2GA_SHIFT                            27 // min.: 0, max.: 1, default: 0
	#define TMC2130_S2GB_MASK                             0x10000000 // DRV_STATUS //
	#define TMC2130_S2GB_SHIFT                            28 // min.: 0, max.: 1, default: 0
	#define TMC2130_OLA_MASK                              0x20000000 // DRV_STATUS //
	#define TMC2130_OLA_SHIFT                             29 // min.: 0, max.: 1, default: 0
	#define TMC2130_OLB_MASK                              0x40000000 // DRV_STATUS //
	#define TMC2130_OLB_SHIFT                             30 // min.: 0, max.: 1, default: 0
	#define TMC2130_STST_MASK                             0x80000000 // DRV_STATUS //
	#define TMC2130_STST_SHIFT                            31 // min.: 0, max.: 1, default: 0
	#define TMC2130_PWM_AMPL_MASK                         0xFF // PWMCONF // User defined PWM amplitude offset (0-255) The resulting amplitude (limited to 0-255) is: PWM_AMPL + PWM_GRAD * 256 / TSTEP
	#define TMC2130_PWM_AMPL_SHIFT                        0 // min.: 0, max.: 255, default: 0
	#define TMC2130_PWM_GRAD_MASK                         0xFF00 // PWMCONF // Velocity dependent gradient for PWM amplitude: PWM_GRAD * 256 / TSTEP is added to PWM_AMPL
	#define TMC2130_PWM_GRAD_SHIFT                        8 // min.: 0, max.: 255, default: 0
	#define TMC2130_PWM_FREQ_MASK                         0x030000 // PWMCONF // PWM frequency selection
	#define TMC2130_PWM_FREQ_SHIFT                        16 // min.: 0, max.: 3, default: 0
	#define TMC2130_PWM_AUTOSCALE_MASK                    0x040000 // PWMCONF // PWM automatic amplitude scaling
	#define TMC2130_PWM_AUTOSCALE_SHIFT                   18 // min.: 0, max.: 1, default: 0
	#define TMC2130_PWM_SYMMETRIC_MASK                    0x080000 // PWMCONF // Force symmetric PWM
	#define TMC2130_PWM_SYMMETRIC_SHIFT                   19 // min.: 0, max.: 1, default: 0
	#define TMC2130_FREEWHEEL_MASK                        0x300000 // PWMCONF // Allows different standstill modes
	#define TMC2130_FREEWHEEL_SHIFT                       20 // min.: 0, max.: 3, default: 0
	#define TMC2130_PWM_AMPL_MASK                         0xFF // PWMCONF // User defined maximum PWM amplitude when switching back from current chopper mode to voltage PWM mode (switch over velocity defined by TPWMTHRS). Do not set too low values, as the regulation cannot measure the current when the actual PWM value goes below a setting specific value. Settings above 0x40 recommended
	#define TMC2130_PWM_AMPL_SHIFT                        0 // min.: 0, max.: 255, default: 0
	#define TMC2130_PWM_GRAD_MASK                         0xFF00 // PWMCONF // User defined maximum PWM amplitude change per half wave (1 to 15)
	#define TMC2130_PWM_GRAD_SHIFT                        8 // min.: 0, max.: 15, default: 0
	#define TMC2130_PWM_FREQ_MASK                         0x030000 // PWMCONF // PWM frequency selection
	#define TMC2130_PWM_FREQ_SHIFT                        16 // min.: 0, max.: 3, default: 0
	#define TMC2130_PWM_AUTOSCALE_MASK                    0x040000 // PWMCONF // PWM automatic amplitude scaling
	#define TMC2130_PWM_AUTOSCALE_SHIFT                   18 // min.: 0, max.: 1, default: 0
	#define TMC2130_PWM_SYMMETRIC_MASK                    0x080000 // PWMCONF // Force symmetric PWM
	#define TMC2130_PWM_SYMMETRIC_SHIFT                   19 // min.: 0, max.: 1, default: 0
	#define TMC2130_FREEWHEEL_MASK                        0x300000 // PWMCONF // Allows different standstill modes
	#define TMC2130_FREEWHEEL_SHIFT                       20 // min.: 0, max.: 3, default: 0
	#define TMC2130_PWM_SCALE_MASK                        0xFF // PWM_SCALE // Actual PWM amplitude scaler (255=max. Voltage) In voltage mode PWM, this value allows to detect a motor stall.
	#define TMC2130_PWM_SCALE_SHIFT                       0 // min.: 0, max.: 255, default: 0
	#define TMC2130_INV_MASK                              0x01 // ENCM_CTRL //
	#define TMC2130_INV_SHIFT                             0 // min.: 0, max.: 1, default: 0
	#define TMC2130_MAXSPEED_MASK                         0x02 // ENCM_CTRL //
	#define TMC2130_MAXSPEED_SHIFT                        1 // min.: 0, max.: 1, default: 0
	#define TMC2130_LOST_STEPS_MASK                       0x0FFFFF // LOST_STEPS // Number of input steps skipped due to higher load in dcStep operation, if step input does not stop when DC_OUT is low. This counter wraps around after 2^20 steps. Counts up or down depending on direction.
	#define TMC2130_LOST_STEPS_SHIFT                      0 // min.: 0, max.: 1048575, default: 0


#endif /* TMC2130_MASK_SHIFT_H */
